name: "Bug"
description: "Relato de problema com passos de reprodução."
title: "[bug] "
labels: ["type:bug"]
body:
  - type: dropdown
    id: mode
    attributes:
      label: Modo de conexão
      description: "Qual modo estava ativo quando o bug ocorreu?"
      options:
        - "Direct"
        - "VPN/Overlay"
        - "Relay (Pro)"
        - "Desconhecido"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - "web"
        - "server"
        - "webrtc"
        - "sfu"
        - "connectivity"
        - "pro"
        - "infra"
        - "docs"
        - "unknown"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Resumo
      placeholder: "O que está quebrado?"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Passos para reproduzir
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Ambiente
      description: "Browser/OS, rede/VPN (se houver), commit/versão, logs."
      placeholder: |
        Browser:
        OS:
        Rede (Wi-Fi/Cabo/4G):
        VPN (se houver):
        Commit/Tag:
        Logs:
