name: "Spike / Pesquisa"
description: "Explorar alternativas e reduzir incerteza técnica."
title: "[spike] "
labels: ["type:spike"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - "webrtc"
        - "sfu"
        - "connectivity"
        - "pro"
        - "infra"
        - "web"
        - "server"
        - "docs"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Pergunta a responder
      placeholder: "Ex.: como forçar/diagnosticar Direct vs Relay? Qual política de quotas no Pro?"
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Abordagem
      value: |
        - O que vamos testar?
        - Quais métricas/saídas?
    validations:
      required: true

  - type: textarea
    id: deliverable
    attributes:
      label: Saída esperada
      placeholder: "Documento com decisão + mini POC + trade-offs."
    validations:
      required: true
